### ISSUE TITLE
typo in volantino_fronte.html

### ISSUE THREAD

**Issue by mone27** [MozillaItalia/firefox-vademecum#104]
manca uno spazio davi a globo 
![image](https://user-images.githubusercontent.com/17617810/39666013-1a827340-509d-11e8-8533-2ae3b989568a.png)
faccio una pull request ( non so se preferite issue o pr)

**Comment by Sav22999** [comment]
Fai pr la accetto

**Comment by Sav22999** [comment]
Errore corretto
