### ISSUE TITLE
aggiungere in README.md come fare a generare html e pdf

### ISSUE THREAD

**Issue by mone27** [MozillaItalia/firefox-vademecum#109]
Io sto provando a fare delle modifiche al volantino, ma non sapendo come viene generato il pdf non posso vedere il risultato finale che sistema è stato utilizzato?
L'html è copiato a mano o ci sta uno script che va da vademecum.md a volantino.html.

**Comment by Mte90** [comment]
Hai ragione mancano queste istruzioni, al momento la conversione md/html è effettuata manualmente e il pdf viene generato dalla versione html una volta che le modifiche sono finite.
Dobbiamo documentare la procedura di contribuzione, che ne dici @Sav22999.
Si parte dalla versione md e quando si ritiene ora si passa alla versione html e infine pdf.
Sarebbe da vedere come automatizzarla, forse con pandoc (per il momento tralscerei questa parte).

**Comment by mone27** [comment]
Condivido che automatizzare non ha un'elevata priorità. Solo che vorrei evitare di fare una PR che incasina tutto il layout e non posso controllare prima. Quindi @Sav22999 se puoi dirci il tool che usi per la conversione.

**Comment by Mte90** [comment]
Credo che il pdf usa chrome (gliel'ho suggerito io) ma per le pr non c'é bisogno di preoccuparsi di modificare html e pdf. Lo faremo noi quando ci saranno diverse richiesteperò sicuramente va documentato.

**Comment by mone27** [comment]
Ma io vorrei vedere anche il risultato finale!

**Comment by Sav22999** [comment]
Sisi, lo documento subito!

Non ho capito che risultato finale vuoi vedere?
________________________________

**Comment by Mte90** [comment]
Di solito lo facciamo poco dopo, altrimenti dobbiamo inventarci una soluzione automatizzata per semplificare i passaggi.

**Comment by mone27** [comment]
Vorrei vedere se una sezione è troppo lunga per entrare nello spazio riservato dal css  e evitare testo con font schiacciato o in parte con il testo troncato

**Comment by Sav22999** [comment]
Per vedere se esci o meno dallo spazio basta che scarichi sia il css sia l'html (anche soltanto il fronte o il retro, non per forza entrambi) e li apri, una volta scaricati, con un web browser... e vedi come esce l'html... (ovviamente modifica sul tuo computer quello che vuoi direttamente sull'html)... questa è l'unica soluzione che mi viene in mente

**Comment by mone27** [comment]
Già fatto..... Ma su firefox  mi da problemi con la versione non modificata... Quindi prima di dire che c'era qualcosa che non andava volevo capire come veniva fatto il rendering definitivo

**Comment by Sav22999** [comment]
Ho capito... mi spiace

Cerchiamo di risolvere il problema se vuoi... non dovrebbe dare alcun problema 🤔

**Comment by Sav22999** [comment]
Comunque @mone27  non preoccuparti, apporta le modifiche direttamente su vademecum.md. Io, poi, aggiorno l'HTML e ti avviso... so che è acerbissima come procedura...

**Comment by mone27** [comment]
Okay va bene, non è un problema perchè tanto penso che le modifiche non saranno molte.
Non c'entra niente ma per fare il pdf usi chrome?

**Comment by Sav22999** [comment]
No no, non so se posso dire il nome del software qui... hai Telegram?

**Comment by Sav22999** [comment]
Issue risolto. E' stato integrato nel file README la modalità di conversione html->pdf (mi ero dimenticato di chiudere l'issue. scusate)
