### ISSUE TITLE
inserire qr nel vademacum versione tecnica

### ISSUE THREAD

**Issue by mone27** [MozillaItalia/firefox-vademecum#110]
Un'idea che mi è venuta è inserire un QR nel vademecum che punta a mozillaitalia.org o magari a una pagina con tutti link utili. Perché penso che sia un sistema comodo per passare dal vademecum (che per forza deve essere sintetico) al web dove trovi informazioni in abbondanza.
Pensavo a qualcosa di non troppo grande tipo:
![image](https://user-images.githubusercontent.com/17617810/39863899-4f7807a0-5448-11e8-85e9-cb058e5379bb.png)
da mettere o in alto a destra nella prima pagina  o in fondo a destra vicino a contributori.
@Sav22999 non quando questo possa incasinare il layout e i css.

**Comment by Mte90** [comment]
Non so se abbiamo spazio per inserirlo anche se non sarebbe male metterlo.

**Comment by mone27** [comment]
penso che a questo deve rispondere @Sav22999 che lui che ha fatto la grafica. Secondo me in basso a destra a occhio c'entra ma non se viene una cosa oscena.

**Comment by Sav22999** [comment]
Oddio. L'idea è bellissima... avevo la stessa idea, inoltre volevo mettere anche il logo Mozilla Italia (magari se riusciamo(riescono) a fare quello nuovo)... non c'era spazio e non sapevo come piazzarcelo...
Se volete provo, però sarebbe più bello (se entra) mettere tutti i loghi ufficiali... tipo vorrei mettere quello di Firefox, Mozilla Italia, CC License, Mozilla e QR code... non si può?
________________________________

**Comment by mone27** [comment]
Secondo me si potrebbe  ricavato mettere i loghi

**Comment by Mte90** [comment]
Vediamo prima se riusciamo a salvare spazio con una versione temporanea, se ci riusciamo poi vediamo come riempirlo

**Comment by Sav22999** [comment]
Si, appena posso vedo di farlo ok? Vi faccio sapere

**Comment by mone27** [comment]
Forse per salvare spazio si potrebbe rimpicciolire la fascia nera intorno ai titoli

**Comment by Sav22999** [comment]
Ho riflettuto. Lo spazio riesco anche a ricavarlo, ma ho pensato che inserire un codice QR così, messo a casaccio sembra molto male. Secondo me ci starebbero solamente i loghi (nella versione generale). Piuttosto, inserirei **vari** codici QR in una futura versione tecnica. L'utente medio credo conosca poco come usare un codice QR (se sa cos'è)...
Mentre in un documento più tecnico ci starebbe, fatemi sapere cosa ne pensate

**Comment by Mte90** [comment]
Solo nella versioen tecnica non sembra una pensata sbagliata li, il amteriale sarà diverso e forse anche meno esplicativo e quindi ricavare spazio non sarebbe un problema.

**Comment by Sav22999** [comment]
Esatto, poi magari si potrebbe inserire un QR che manda a Firefox, uno che rimanda a Firefox Focus, ecc. penso sia meglio.... come disse il mio prof. di italiano (e storia): "Meglio fare poco, ma farlo bene" :)

**Comment by Sav22999** [comment]
Quindi, a vostro parere, è meglio inserire i solo i loghi, inserire sia i loghi sia il qr, o non mettere niente e lasciare così?

**Comment by Mte90** [comment]
Direi che questo lo vediamo una volta che abbiamo il testo per il volantino tecnico così a seconda dello spazio vediamo cosa fare.

**Comment by Sav22999** [comment]
(@Mte90 stavo modificando il post xD a cui sopra hai risposto)

**Comment by mone27** [comment]
Secondo me anziché mettere più QR conviene metterlo uno solo che rimanda a una pagina piena di link (che cosi possiamo aggiornare senza modificare il QR che magari abbiamo già stampato)

**Comment by Sav22999** [comment]
I QR possono essere anche dinamici :)

**Comment by mone27** [comment]
Ma ci sta un sito che te lo fa diventare dinamico e poi non so se l'utente con 10 qr non ci capisce più niente

**Comment by Sav22999** [comment]
No, ma mica 10. Comunque è indirizzato per utenti più esperte, quindi non dovrebbe essere un problema.

Al massimo si potrebbe mettere massimo un QR per sessione. Ad esempio per "Altri progetti" un QR che manda a una pagina contentente TUTTI i progetti nel dettaglio. è una mia idea, comunque, discutiamone apertamente :)

**Comment by Mte90** [comment]
Senza il testo è difficile valutare quali qr mettere, quindi direi che questo ticket può essere valutato quando abbiamo una proposta di testo.

**Comment by Sav22999** [comment]
Perfetto
________________________________
