### ISSUE TITLE
Sezioni vademecum vt

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/firefox-vademecum#113]
Questo issue è dedicato ala versione tecnica (vt) del vademecum, più precisamente per dialogare sulle sezioni da integrare

**Comment by Sav22999** [comment]
Io avrei pensato a qualche sezione che potrebbe essere integrata; datemi una vostra opinione.
- Presentazione
- Diventa volontario Mozilla Italia
(penso siano scontate)

- Sezione dove vengono descritti gli strumenti utilizzati in Mozilla Italia, quindi github, pontoon, ecc. (descrivere nel dettaglio ciascuno strumento)
- Firefox Quantum e le novità, a livello tecnico, introdotte (Stylo, ecc.)
- Estensioni (a livello più tecnico) quindi io ci metterei tipo VPN, e cose così
- Sempre nella sezione Estensioni, come sviluppare una propria estensione (i metodi e linguaggi disponibili)
- Tipi di versione di Firefox, dando una breve descrizione alla Stabile e alla Beta e dettagliando la Nightly, la ESR e la Dev Edition

**Comment by Sav22999** [comment]
- Presentazione
Innanzitutto è doveroso spiegare che cos'è Firefox. È un browser web unico che mette al primo posto gli utenti, ha il codice sorgente libero (quindi tutti possono analizzarlo e modificarlo), è disponibile per tutti i principali sistemi operativi, è personalizzabile, è versatile, è veloce e, molto importante, è sicuro. Mozilla Foundation è l'organizzazione senza fini di lucro che, da oltre 15 anni, supporta Firefox e altri numerosi progetti. Questa organizzazione ha più di 10.000 volontari, provenienti da ogni parte del globo. La comunità che opera in Italia prende il nome di Mozilla Italia; si occupa di tradurre progetti e siti web, ma anche di realizzare e partecipare a eventi, aiutare gli utenti, e molto altro. Per questi motivi chiunque è il benvenuto: la collaborazione è il fulcro di ogni comunità. Trovi Mozilla Italia sia sul forum (forum.mozillaitalia.orgs) sia sui canali Telegram (@mozItaHub).

- Perchè scegliere Firefox?
Firefox è creato dagli utenti per gli utenti. Non è realizzato per guadagnare (Mozilla è una fondazione no profit), ma per offrire un'esperienza di navigazione unica. Scegli il browser libero, sicuro, affidabile e indipendente. Scegli Firefox!

- Strumenti utilizzati dai volontari
I volontari di Mozilla Italia utilizzano quotidianamente diversi strumenti, sviluppati specificatamente per ogni settore; ad esempio il team di localizzazione (L10N) utilizza anche la piattaforma Pontoon.
|| . . GitHub . . || -- || . . Pontoon . . ||
|| (descrizione) || -- || (descrizione) ||

- Siamo una comunità
Mozilla Italia, come comunità, organizza almeno una call mensile per poter discutere di tutti gli aggiornamenti......
Alla call può partecipare chiunque, anche chi non fa parte dei volontari.

- Estensioni
Firefox è il web browser per eccellenza per quanto riguarda il numero e la qualità delle estensioni. Se non trovi quella che fa al caso tuo puoi tranquillamente svilupparla tu stesso.
|| [<estensione>] || -- || Crea la tua estensione ||
|| (descrizione) || -- || (descrizione) ||

- Scegli la giusta versione di Firefox
Firefox è disponibile in molte versioni, ciascuna pensata per utenza differente. Scoprile tutte:
|| Stabile || -- || Beta || -- || Nightly || -- || Dev Edition || -- || ESR ||

- Unisciti a noi. Diventa volontario Mozilla Italia!
[...]

- Collaboratori
[...]

**Comment by Mte90** [comment]
Dobbiamo decidere se il volantino tecnico è pensato per contribuire o sviluppare oppure per approfondire la parte tecnica di quello espresso nella versione normale.

Non vorrei che diventi un polpettone con tanta roba e non è chiaro il target di persone a cui vogliamo puntare.

**Comment by Sav22999** [comment]
Certo. Io penso sia meglio realizzare un vademecum per tecnici/sviluppatori, quindi trattare gli argomenti più da un punto di vista tecnico. Però magari aprire un ticket apposito (o nel forum) sarebbe l'ideale così tutti possano esprimere il proprio parere

**Comment by Mte90** [comment]
Allora toglierei la parte contribuire e quindi farei un elenco di tecnologie pensate da usare per sviluppare.

Quindi:

* Rust
* WebVR
* Addons

Poi una sezione a tecnologie da sperimentare:

* Deep Speech (common voice)
* Servo
* Debugger.Html

In cima a tutto questo un elenco delle novità della versione quantum così si introducono meglio la maggior parte di queste cose.

**Comment by mone27** [comment]
Penso che possa andare bene, se vuoi collaborare e non sai molto di informatica in quello generico ci sta tutto. In questo tecnico mettiamo i dettagli su come funziona e come sviluppare firefox ( e altri progetti mozilla tipo iot)

**Comment by Sav22999** [comment]
Quindi, @mone27 sei per non mettere per niente la sezione?

**Comment by Sav22999** [comment]
Non mettendo niente mi sembra come se volessimo presentare solo la comunità, ma non "cerchiamo" altri volontari.... almeno una frasi alla fine del tipo "Vuoi collaborare? Visita _TALdeiTALI_"

**Comment by mone27** [comment]
No come hai detto te sezione collabora piccola piena di link e magari con QR

**Comment by Sav22999** [comment]
Si, se c'è spazio. Altrimenti basta una frasi "piccina picciò" alla fine xD

**Comment by Mte90** [comment]
Allora fate una bozza solo md delle varie sezioni che pensate così poi ci discutiamo sopra e vediamo di fare i testi ecc :-)

**Comment by Sav22999** [comment]
![](https://i.imgur.com/5PJY19T.jpg)
![](https://i.imgur.com/sU42XP7.jpg)

**Comment by Sav22999** [comment]
Le sezioni sono state decise, ora è necessario solamente svilupparle a fondo.
Direi di chiudere questo issue.

Riporto le sezioni, comunque:
* Presentazione
* Firefox
    * Add-ons
    * Stylo
    * WebVR
    * Rust
* Internet Health Report
* Test Pilot
    * Send
    * Notes
* Altri esperimenti
    * Common Voice
    * Servo
    * MDN
* Strumenti utilizzati
    * Forum
    * Pontoon
    * GitHub
* Unisciti a noi. Diventa un volontario di Mozilla Italia ora!
* Collaboratori
