### ISSUE TITLE
script per convertire da markdown a html

### ISSUE THREAD

**Issue by mone27** [MozillaItalia/firefox-vademecum#116]
Per poter fare una build completamente automatica è necessario avere uno script che converte Vademecum.md in volantino.html.
Per fare questo non so che tecnologia conviene usare, di sicuro u convertitore md/html per gestire titoli, grassetti.. Il problema che io vedo è inserire nell'html correttamente id e class per avere il css visualizzato.
@Mte90 aveva consigliato di provare a guardare pandoc, oppure non se esiste qualche altra cosa provo a vedere.

**Comment by Mte90** [comment]
Si possono fare dei file di template anche in markdown che poi possono essere elaborati e convertiti.
Bisogna andare di tentatvi di con diversi strumenti, pandoc è uno di questi ma ce ne sono molti in giro.

**Comment by mone27** [comment]
Okay se per voi non è un problema cercherei  qualcosa in python su cui ho una maggiore esperienza.

**Comment by Mte90** [comment]
L'importante è avere lo strumento al momento il linguaggio non è un problema.

**Comment by mone27** [comment]
ho iniziato a guardare pandoc, vi aggiorno per la situazioen attuale.
Utilizzando [markdow php extra](https://michelf.ca/projects/php-markdown/extra/) (supportato da pandoc) permette di mettere html inline e di inserire markdown dentro html
`<div id=sez1 markdown=1>
questo è *markdown*

</div>
`
che poi con `pandoc -f markdown_phpextra -t html -o output.html input.md` si converte in html.
Il sistema funziona ma il markdown è un po' appesantito .
Fatemi sapere se può andare o conviene cercare qualcosa di meglio

**Comment by mone27** [comment]
non ci ho più lavorato ma il tool praticamente già funziona, la realizzazione di VT potrebbe essere proprio l'occasione per sfruttare questo nuovo sistema.
Bisogna scrivere i tag html nel markdown. Io avevo già iniziato a aggiornare la Versione normale se servo lo finisco.

**Comment by Sav22999** [comment]
Era proprio questo il punto. Invece di "sprecare" ora forze su questa cosa avevo pensato di concentrarci su VT. Anche perché dopo averla finita ci vuole una lunga revisione da parte della community, nostra nuovamente, eccetera. Però, se è quasi finito possiamo provare. Perché no, ti do una mano se vuoi :) il problema sono i contenuti.

**Comment by Mte90** [comment]
Si confermo, teniamo questo task per il dopo evento :-)

**Comment by Sav22999** [comment]
Comunque, dopo attenta analisi, sono venuto alla conclusione che questo processo non ha alcun senso e spiego perchè:
Il file MD non sarebbe quello "puro", che più o meno tutti riescono a comprendere, infatti sarebbe necessario, comunque, inserire tag HTML al suo interno quindi diverrebbe un file MD-HTML (un incrocio tra i due). Personalmente non reputo una cosa utile in quanto, effettivamente, si potrebbe modificare direttamente dall'HTML e si otterrebbe la stessa cosa.
Si opera, invece, in questa maniera (quindi manualmente da MD a HTML) in quanto si verifica in tempo reale le effettive dimensioni, se il contenuto entra negli appositi spazi.
Pertanto, concludendo, mi dimostro contrario a questo "progetto" seppur lodevole.

**Comment by Mte90** [comment]
Potremmo vedere un sistema di template ovvero che lo script riconosce i vari blocchi del markdown e li inserisce nel codice html nei posti giusti così da evitare la parte manuale.

**Comment by Sav22999** [comment]
Sisi. Comunque ci dedichiamo dopo. (Ho scritto altrimenti mi dimenticavo)

**Comment by Sav22999** [comment]
Bene, direi che ci si può dedicare a questo issue, o no?
@mone27 @Mte90 cosa ne pensate?

**Comment by Mte90** [comment]
assolutamente avete il via libera

**Comment by mone27** [comment]
Sì troppa automazione non serve tanto il vademecum è più o meno fatto.

**Comment by Sav22999** [comment]
Ma in un futuro le tematiche, le sezioni e i contenuti verranno aggiornati e potrebbe essere utile.
