### ISSUE TITLE
Ottimizzare foglio di stile VG (stile_VG.css)

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/firefox-vademecum#117]

**Comment by Sav22999** [comment]
Ragazzi, ho un dubbio.
Nell'ottimizzazione, ho sintetizzato raggruppando tutte le sezioni in un unico blocco
```
sez1, sez2, .., sezN
{
}
```
sono indeciso se lasciare le sezioni sez2, .., sezN come blocchi inserendo un commento del tipo "/*vedere sopra*/" oppure rimuoverli direttamente (questo per semplificare una futura non mia revisione, quindi affinché chiunque sia in grado di comprendere il codice facilmente)

Che ne pensate, voi?

---proposta 1---
```
sez1, sez2, sezN
{
... --> codice effettivo
}
sez2
{
/*vedere sopra*/
}
sezN
{
/*vedere sopra*/
}
```

---proposta 2---
```
sez1, sez2, sezN
{
... --> codice effettivo
}
```

(io sono più per la ---proposta 2--- ma chiedo consiglio a voi 😄 )

**Comment by Mte90** [comment]
Non ha senso la parte vedere sopra, un dev riesce a ritrovare i selettori utilizzando gli strumenti di sviluppo del browser quindi non è necessario.

**Comment by Sav22999** [comment]
Si, io ho chiesto proprio per questo... non ho mai lavorato in grandi progetti, dove molte persone devo successivamente riutilizzare/rivederlo/riadattarlo, in genere i progetti a cui ho partecipato li revisionavo nuovamente io... per cui credo sia meglio chiedere piuttosto che fare e sbagliare, no?
