### ISSUE TITLE
Errori di battitura

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/firefox-vademecum#127]
Nel Vademecum VT:
- Pag. 2, paragrafo "Common Voice": "...esse vAngano pronunciate..."
- Pag. 2, titolo "Unisciti a noi": "...diventa un voLOTario..."

Segnalati dai linux day!

**Comment by Sav22999** [comment]
Caspita, che ignoranti 😭

**Comment by Mte90** [comment]
Correzioni fatte dobbiamo fare i nuovi html/md ci pensi te @Sav22999?

**Comment by Sav22999** [comment]
Si. Dopo faccio

**Comment by Sav22999** [comment]
@Mte90 le correzioni le ho appoetate da tempo. Non ho chiuso ancora l'issue perché non ho avuto il tempo di aggiornare i PNG e i PDF. Ci pensi tu?

**Comment by Sav22999** [comment]
✔️  corretti da già diverso tempo, chiudo questo issue
