### ISSUE TITLE
Barra degli indirizzi intelligente

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/firefox-vademecum#14]
Aggiungere qualche riferimento a https://support.mozilla.org/it/kb/Barra%20degli%20indirizzi%20intelligente https://twitter.com/mozillaitalia/status/741387020421992448 potrebbe essere interessante per la promozione

**Comment by Mte90** [comment]
Potremmo mettere questa sezione come Hot Tip solo se abbiamo spazio nella versione a due pagine ma dovremmo pensare ad un breve testo.

**Comment by Mte90** [comment]
Il mio testo:
```
Barra degli indirizzi intelligente
Si possono utilizzare dei caratteri speciali che si comportano da filtri, * per cercare nei segnalibri o ^ nella cronologia. Scoprili tutti su https://mzl.la/2mH72ZQ
```
Credo che lo potremmo mettere al posto del pulsante Dimentica.

**Comment by Fastbyte01** [comment]
Barra degli indirizzi intelligente
Dalla versione 57 di Firefox è possibile utilizzare dei caratteri speciali come filtri, per esempio * per effetuare una ricerca nei segnalibri oppure ^ per effettuare una ricerca nella cronologia. Scoprili tutti su https://mzl.la/2mH72ZQ

**Comment by mone27** [comment]
Il link che hai messo alla fine a me da pagina non trovata

**Comment by Mte90** [comment]
Nuovo link: http://mzl.la/1zazb0J

**Comment by Sav22999** [comment]
```
Dalla versione 57 di Firefox è possibile utilizzare dei caratteri specifici, direttamente dalla barra degli indirizzi, per interagire con la stessa. Scoprili tutti su http://mzl.la/1zazb0J
```
Io proporrei questo, e se c'è delle spazio ulteriore da poter usare nel volantino poi di aggiungere degli esempi

**Comment by Mte90** [comment]
dove proponi di inserirlo?

**Comment by Sav22999** [comment]
Come descrizione della "Barra degli indirizzo intelligente".

**Comment by Mte90** [comment]
Vai di pr
