### ISSUE TITLE
Formato pdf

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/firefox-vademecum#23]
Potremmo fare uno script che genera un pdf (con un build bot) cosi incominciamo a lavorare anche dal punto di vista output.
Dovremmo rientrare nelle 2 pagine in modo che sia possibile stamparlo fronte retro ma non necessariamente, quindi prevedere anche una pagina.

**Comment by edovio** [comment]
Potremmo utilizzare l'estensione per GitHub di GitBook (https://www.gitbook.com/). Il Pdf viene generato immediatamente.

**Comment by Mte90** [comment]
allora secondo me non va bene, avendo esperienza con leanpub direi che dobbiamo prima fare dei testi manuali perché quello é fatto per dei libri a noi serve per un volantino

**Comment by MirkoPizii** [comment]
Stavo creando la versione PDF però mi sono accorto che non ci stiamo nelle due pagine considerando l'ottimizzazione dello spazio e la minima dimensione leggibile del carattere.

Quello che manca è le tre sezioni relative a "**Altri progetti Mozilla**", "**Vuoi contribuire?**" e infine una aggiuntiva "**Crediti**" che contiene i nomi degli autori.

![pagina1](https://cloud.githubusercontent.com/assets/1420426/19322187/576b8126-90b8-11e6-8096-7a60e6686e23.png)
![pagina2](https://cloud.githubusercontent.com/assets/1420426/19322188/5772646e-90b8-11e6-87e1-79eb2a650a70.png)

Come avete potuto osservare, si andrebbe a creare la terza pagina.. Che si fa?

**Comment by Mte90** [comment]
Forse possiamo tagliare una riga a modalità di lettura ("web elementi non necessari." senza gli esempi) e XNotifier (la seconda frase) cosi guadagniamo un pò di spazio.

Per Privacy badger c'é una piccola correzione non é "riconoscono le pubblicità malevoli" ma le risorse malevoli o impiccione, ma farò un commit a riguardo.

A questo punto cambierei il testo di "Altri progetti Mozilla" togliendo l'ultima frase citando Thunderbird in quell'elenco e non mettendo quel testo di esempio cosi abbiamo spazio per l'ultima sezione e gli autori.
Che ne pensate @edovio @tissy9491?

PS: complimenti a @MirkoPizii per il lavoro grafico!

**Comment by edovio** [comment]
Si potremo fare anche così. Nel caso facciamo una short guida differente per diventare un Volontario

**Comment by tissy9491** [comment]
Va bene, io darei una accorciatina anche a DownTheMall,  da "Consentendo" a "Molto di più"
Ps. Complimenti anche da parte mia per la grafica e l'impaginazione, semplice e di impatto
