### ISSUE TITLE
Sezione Estensioni

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/firefox-vademecum#36]
Io direi che possiamo togliere:

- Profilist
- Xnotifier
- Cryptocat
- Video Resumer

Al loro posto mettere:

- I don't care about cookies - https://addons.mozilla.org/it/firefox/addon/i-dont-care-about-cookies/
- Dictionary Switcher - https://addons.mozilla.org/it/firefox/addon/i-dont-care-about-cookies/
- Https Everywhere - https://addons.mozilla.org/it/firefox/addon/https-everywhere/
- uBlock Origin - https://addons.mozilla.org/it/firefox/addon/ublock-origin/

**Comment by edovio** [comment]
potremo mettere Https Everywhere e ZenHub :)

**Comment by Mte90** [comment]
Https everywhere aggiudicato, mentre zenhub é troppo github focused. Al momento le estensioni sono generiche per tutti i siti o funzionalità del browser.
Potremmo metterei l'estensione No more 404 nato in test pilot.

**Comment by Mte90** [comment]
Ho aggiornato il primo commento con le modifiche che vanno fatte

**Comment by tissy9491** [comment]
D'accordissimo su tutto, faccio notare però a Daniele che il link per dictionary switcher è lo stesso di don't care about cookies

**Comment by Mte90** [comment]
Tanto il Link sul vademecum non serve, serve a noi come riferimento per la
descrizione.
Direi che è ora che qualcuno faccia una pr

Il 20 mar 2017 19:42, "Irene Pirrotta (tissy)" <notifications@github.com>
ha scritto:

D'accordissimo su tutto, faccio notare però a Daniele che il link per
dictionary switcher è lo stesso di don't care about cookies

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MozillaItalia/firefox-vademecum/issues/36#issuecomment-287858497>,
or mute the thread

**Comment by tissy9491** [comment]
Arrivo
