### ISSUE TITLE
Sezione Novità

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/firefox-vademecum#37]
Direi di sostituire:

- Do not track (oramai é una funzionalità presente da anni)

Sostiturila con:

- Firefox Nightly (cosi facciamo girare la voce)

**Comment by edovio** [comment]
Si son d'accordo, magari parlerei sia di Nightly che di Firefox for Dev

**Comment by Mte90** [comment]
La dev non si sa che fine fa' quindi io eviterei.
Il testo che pensavo per la nightly:
```
Firefox Nightly
Una versione di Firefox di sviluppo aggiornata ogni giorno che permette di provare le ultime funzionalità. Utilizzata per segnalare problemi sia di traduzione che di funzionalità e divertirsi provando le ultime novità.
```

**Comment by tissy9491** [comment]
Non lo so, io la evidenzerei lo stesso quantomeno citandola appena, se dobbiamo rivolgerci sia a sviluppatori che utenti, non tutti sanno di questa utile funzione 
Per la nightly sono d'accordo ad inserirla, anche se della dev io ne parlerei sempre e comunque (personalmente)

**Comment by Mte90** [comment]
Formula un nuovo testo allora è vediamo come suona!

Il 20 mar 2017 7:39 PM, "Irene Pirrotta (tissy)" <notifications@github.com>
ha scritto:
