### ISSUE TITLE
Sezione altri progetti

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/firefox-vademecum#38]
Direi che possiamo sostituire Rust con una sezione riguardo i Mozilla Campus club e Mozilla Club..
Rust é troppo tecnico e il volantino epr me deve essere piu per gente comune. Di rust possiamo parlarne a voce con altri swag.

**Comment by edovio** [comment]
Io parlerei di WebVR. Molto probabilmente il Vadevecum va a sviluppatori e utenti. Mediamente non è detto che siano interessati ai Clubs

**Comment by Mte90** [comment]
Esatto, poi abbiamo i file digitali per le cartoline di afram e rust quindi possiamo pensare di toglierli proprio.
Cosi lo rendiamo general purpose e meno per sviluppatori.

**Comment by Mte90** [comment]
Il mio testo per la WebVR:
```
WebVR
La realtà virtuale oggi ci permette di sperimentare nuove possibilità con la realtà aumentata. Oggi queste tecnologie richiedono costosi headset, computer molto potenti o specifici applicativi. Il web invece permette di poter provare queste tecnologie dal vostro browser preferito, permettendovi di usare la VR sia da computer che da mobile con Firefox.  
In Mozilla con A-Frame (libreria JS per la VR) si è creata una comunità che si occupa di promuovere e far sperimentare la realtà virtuale tramite tecnologie facili ed accessibili di tipo web sul sito http://mozvr.com
```

**Comment by Sav22999** [comment]
Ma questa modifiche del RUST sostituito con WebVR quando la si fa? Si può rielaborare un po' la descrizione?

**Comment by Sav22999** [comment]
> La realtà virtuale oggi permette di sperimentare nuove possibilità, anche unita alla realtà aumentata.
Queste tecnologie oggi richiedono costosi headset, dispositivi potenti e specifici. Tutto ciò si può risolvere Grazie al web, grazie a Firefox, sia da mobile sia da desktop.
In Mozilla è stata creata una comunità che si occupa di promuovere e far sperimentare ciò con la libreria js A-Frame, specifica per la VR: http://mozvr.com

**Comment by Mte90** [comment]
Finché il testo non è approvato si può rielaborare :-)

`far sperimentare ciò con la libreria js A-Frame,` direi di sostituirlo con `sperimentare con la libreria JavaScript A-Frame`

**Comment by Sav22999** [comment]
In Mozilla è stata creata una comunità che si occupa di promuovere e sperimentare con la libreria JavaScript A-Frame, specifica per la VR: http://mozvr.com

Così?

**Comment by Mte90** [comment]
ok!

**Comment by Sav22999** [comment]
@Mte90 io aggiungerei un "ciò" a quello che dici tu...

**Comment by Mte90** [comment]
vai!

**Comment by Sav22999** [comment]
subito boss ;)
