### ISSUE TITLE
Regole di stile

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/firefox-vademecum#45]
Dopo aver lavorato sulla versione volantino ho notato che abbiamo descrizioni troppo lunghe per le estensioni.
Direi quindi che dobbiamo lavorare per definire delle regole per semplificare il lavoro sul vademecum per evitare di riscrivere i testi da parte del grafico.

**Comment by Sav22999** [comment]
Consiglierei l'impersonalità, ove possibile. Poichè anche se si vuole comunicare una certa "amicizia", comunque si dovrebbe comunicare professionalità.

**Comment by Mte90** [comment]
Direi di fare un file regole-di-stile.md a riguardo.

**Comment by Sav22999** [comment]
Si, perfetto, così le si tengono tutte sott'occhio ed ordinate. Lo fai tu?

**Comment by Sav22999** [comment]
Sono state integrate in contributing.md

**Comment by Sav22999** [comment]
come siam messi con questo issue? xD @Mte90 cosa ne pensi?

**Comment by Mte90** [comment]
Manca qualcosa nelle regole secondo te? Se no chiudi senza problemi, in caso domani si fa un nuovo ticket spiegando cosa manca.

**Comment by Sav22999** [comment]
Non mi sembra manchi qualcosa... viene specificato anche il colore principale utilizzato e altre informazioni specifiche per VG o per VT. Chiudo, in caso, come dice tu, si apre un ulteriore issue in seguito.
