### ISSUE TITLE
Aggiungere riferimenti Telegram

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/firefox-vademecum#48]
Manca un riferimento a @mozitahub nel vademecum

**Comment by Fastbyte01** [comment]
Dove si dovrebbe aggiungere, nella sezione Vuoi contribuire oppure si dovrebbe aggiungere una nuova breve sezione *"Rimani in contatto"* o qualcosa di simile?

**Comment by Mte90** [comment]
bella domanda, considerando gli spazi nella versione pdf forse si fa prima a metterlo da qualche parte con l'icona telegram per fare prima e nel readme.md di menzionarlo in cima.

**Comment by Mte90** [comment]
SU #55 nel nuovo testo è citato telegram, direi che nella versione grafica si può evidenziare meglio con una icona.

**Comment by Mte90** [comment]
il riferimento ora c'é
