### ISSUE TITLE
Nuovo volantino 2.0 in html

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/firefox-vademecum#49]
L'idea nata con @edovio è quella di fare la nuova versione del testo ed in contemporanea fare il volantino in html e css.
Poi useremo un convertitore per il formato pdf in modo tale chesia più semplice mantenerlo e abbandonarei l markdown ed avere il testo solo da una parte.

**Comment by mone27** [comment]
Il risultato deve essere a colori o in bianco e nero?
Oppure che si adatta a entrambi i casi(magari con 2 css diversi)

**Comment by Mte90** [comment]
Io direi a colori che per il bianco e nero ci pensa la stampa così evitiamo altro lavoro.

**Comment by Mte90** [comment]
In ogni caso prima di lavorare sul codice html dobbiamo decidere il layout se mantenerlo oppure no e che il codice realizzato deve supportare il sistema print dei css e riconoscere le due pagine.
Quindi direi che forse è il caso prima di lavorare agli altri ticket.

**Comment by Fastbyte01** [comment]
Una volta che abbiamo un testo il più definitivo possibile possiamo pensare di elaborare l'html. Meglio perchè onestamente la grafica attuale va un pò rivista.

**Comment by Sav22999** [comment]
Lo chiudiamo questo issue? xD

**Comment by Mte90** [comment]
Finché non è completo e approvato direi di no. Al momento è solo caricato ma è completo di tutte le modifiche che volevamo fare?

**Comment by Sav22999** [comment]
Va bene. Allora completiamolo :P
________________________________

**Comment by Mte90** [comment]
ho visto il readme e vista la 1.2, come ci dicono che va bene cambiamo versione e via :-D

**Comment by Sav22999** [comment]
Quindi la cambiamo dopo?
________________________________

**Comment by Mte90** [comment]
direi di si dopo la revisione così è ufficiale
