### ISSUE TITLE
Rimuovere Dictionary Switcher

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/firefox-vademecum#50]
Al momento questo plugi non è più necessario perché le sue funzionalità sono supportate da Firefox stesso.

Idee per alternative:

* share backported ma sono autoreferenziale ma è molto usato
* history autodelete

**Comment by Sav22999** [comment]
History autodelete mi sembra un progetto molto valido, io direi di sostituire dictionary con quest'ultimo.

**Comment by Sav22999** [comment]
Ho appena scoperto che lo sviluppatore di Share backported è un certo Daniele Mte90 Scasciafratte, non ne sapevo nulla. Credo comunque che sia meglio sostituirlo con History autodelete... perchè alla fine è una funzionalità abbastanza più distaccata da Share backported, quindi dalla condivisione su social... ad esempio questa funzionalità è un po' insensata su Android (e credo su iOS anche) perchè c'è il pulsante "Condividi" già integrato... correggetemi se sbaglio :)

**Comment by Mte90** [comment]
Allora history delete vince :-D

ps: Si conosco anch'io questo tale e lo vedo spesso.

**Comment by Sav22999** [comment]
Ahahah ora dobbiamo pensare alla descrizione di "History delete" giusto?

**Comment by Mte90** [comment]
Esatto, che ne dici: 
```Pulisci la tua cronologia periodicamente secondo i tuoi gusti in modo automatico.```

**Comment by Sav22999** [comment]
Si, credo vada benissimo. Breve e che fa capire cosa fa. 👍

**Comment by Sav22999** [comment]
> Pulisci la cronologia di navigazione periodicamente secondo i tuoi gusti in modo automatico e programmato.

**Comment by Sav22999** [comment]
Quindi che si fa, anche per questo issue si fa un pr, sostituendo dictionary switcher con history autodelete?

**Comment by Mte90** [comment]
Si
