### ISSUE TITLE
Aggiornare sezione altri progetti di Mozilla

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/firefox-vademecum#51]
La stringa: `MDN, Mozilla Science, Webmaker, MOSS e MozVR`
Si riferisce al progetto webmaker ormai defunto e mozvr che oramai è uno standard con il nome di WebVR.
Come possiamo sostituirli?

* Internet Health Report
* altre idee?

**Comment by Fastbyte01** [comment]
Penso che realmente interessante per tutti potrebbe essere l'internet healt report oppure nel caso come extra dare più risalto al discorso privacy.

**Comment by Mte90** [comment]
Direi che possiamo fare: `MDN, Open Leadership e Internet Health Report`

**Comment by Sav22999** [comment]
Facciamo una pr anche per questo issue così lo chiudiamo e possiamo fare il retro del volantino?

**Comment by Mte90** [comment]
vai

**Comment by Sav22999** [comment]
Ora che ci penso, è già stata aggiornata la sezione "Altri progetti" o no? c'è firefox focus, test pilot e webvr

**Comment by Mte90** [comment]
Si questo ticket ad oggi direi che è utile per questa definizione
