### ISSUE TITLE
Rimuovere Condivisione articoli

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/firefox-vademecum#53]
La funzionalità con Firefox 57 è stata rimossa in quanto non standard.

Di cosa possiamo parlare? 

* Pocket
* Multiprocesso
* screenshot

**Comment by Fastbyte01** [comment]
Qui alcune idee, si potrebbero anche inserire brevemente tutte e 3, se si riesce a condensare la spiegazione in circa una riga e mezza.

### Firefox Screenshot:
*Firefox Screenshots* è una nuova funzione che permette di catturare, scaricare, collezionare e condividere immagini ("screenshot") dei siti web.  

### Pocket:
*Pocket* è una funzione integrata in Firefox che ti permette di salvare le pagine web con un semplice clic  e leggere successivamente su qualsiasi dispositivo, anche senza connessione ad internet.

### Multiprocesso
La modalità multiprocesso è una funzione di Firefox che permette di mantenere separato il cuore del browser dai contenuti web aperti nelle varie schede. Questo fa si che ogni pagina venga caricata in un processo separato, garantendo quindi una maggiore sicurezza e meno problemi nel caso in cui una pagina si blocchi, dato che questo blocco non impedirà il corretto funzionamento di Firefox.

**Comment by Mte90** [comment]
Pocket è più un servizio che una funzione.
Sull'ultima frase di multiprocesso forse si può semplificare, @sav22999 hai qualche idea?

In ogni caso considerando che lo spazio che abbiamo non è tanto io direi di lasciar perdere il multiprocesso che è una cosa che all'utente medio non interessa.

Rimane la questione screenshot e pocket al posto di condivisione articoli che dobbiamo vedere se riusciamo a stringere il testo.

**Comment by Fastbyte01** [comment]
Ok @Mte90, correggo e concordo con il fatto che il multiprocesso si può togliere, giustamento pensando a quello che è il target medio di chi prende il volantino.

Firefox Screenshot:
Firefox Screenshot è una nuova funzione che permette di catturare, scaricare, collezionare e condividere immagini ("screenshot") dei siti web.

Pocket:
Pocket è un servizio integrato in Firefox che ti permette di salvare le pagine web con un semplice clic e leggere successivamente su qualsiasi dispositivo, anche senza connessione ad internet.

**Comment by Mte90** [comment]
Mi sembra perfetto così!

**Comment by Fastbyte01** [comment]
ok, se va bene cosi faccio il PR con le modifiche.

**Comment by Sav22999** [comment]
Magari invece di "ti permette" è meglio generico "permette"(senza "ti")

**Comment by Mte90** [comment]
fai una pr con il tuo suggerimento :-)
