### ISSUE TITLE
Rimuovere Thunderbird

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/firefox-vademecum#54]
Non essendo chiaro il suo futuro e visto l'interesse oramai di client per la posta da computer minore rispetto a prima potremmo parlare di Firefox Focus per Android e iOS, voi che ne dite?

**Comment by Mte90** [comment]
Al momento nella versione pdf per causa di spazio thunderbird non è presente quindi direi di toglierlo anche dalla versione markdown

**Comment by Fastbyte01** [comment]
Concordo. Ormai i client email offline hanno sempre minor peso. Trovo interessante anche l'idea di parlare di Firefox Focus, che è un ottimo software ma che è passato un pò in sordina per quanto riguarda la promozione.

**Comment by Mte90** [comment]
Ti va di fare una pull request rimuovendo il testo di thunderbird aggiungendone uno per Firefox Focus? Dai che poi aggiungiamo il tuo nome all'elenco :-P

**Comment by Fastbyte01** [comment]
Si, non c'è problema. Appena pronto faccio un pull request sul markdown.

**Comment by Fastbyte01** [comment]
Penso che questo issue si possa chiudere dopo la modifica e2bc7f2

**Comment by Mte90** [comment]
Si da quello che vedo non c'è più thunderbird.
Il punto che adesso il progetto si è rivitalizzato, ma non credo che in ogni caso al momento vale la pena promuovere essendo di nicchia.
