### ISSUE TITLE
Sezione Mozilla Italia

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/firefox-vademecum#55]
Il testo attuale:
`
Mozilla Italia invece è l'associazione italiana, anch'essa no-profit, che si impegna ad aiutare i volontari italiani a tradurre i progetti e le pagine web di Mozilla e a fornire supporto e assistenza a tutti gli utenti. Il punto d'incontro di questi volontari è il forum di Mozilla Italia che conta mediamente dieci nuovi iscritti e cento messaggi scritti ogni giorno.
`

Non siamo più un associazione quindi direi di riformulare:
`
Mozilla Italia invece è la comunità italiana, che si occupa di tradurre i progetti e le pagine web di Mozilla,  fornire supporto e assistenza a tutti gli utenti e in altre attività come eventi. Il punto d'incontro principale è il forum di Mozilla Italia (che conta mediamente dieci nuovi iscritti e cento messaggi scritti ogni giorno) e i nuovi canali Telegram disponibili su @mozItaHub.
`

**Comment by Sav22999** [comment]
"e in altre attività come eventi." non riesco a capire dove si collega... mi sembra una frase messa lì senza connessione. 🤔

**Comment by Mte90** [comment]
come riformuleresti?

**Comment by Sav22999** [comment]
(I'm thinking...)

**Comment by Sav22999** [comment]
Una domanda. "E in altre ..." è riferito a "supporto e assistenza" ?

**Comment by Sav22999** [comment]
> Mozilla Italia invece è la comunità italiana, che si occupa di tradurre i progetti e le pagine web di Mozilla, fornire supporto e assistenza a tutti gli utenti **ed è presente** anche in altre attività, come gli eventi. Il punto d'incontro principale è il forum di Mozilla Italia (che conta mediamente dieci nuovi iscritti e cento messaggi scritti ogni giorno) e i nuovi canali **Telegram, accessibili da @mozItaHub**.

Io la riformulerei così

**Comment by Mte90** [comment]
mi sembra ottima, si va di pr?

**Comment by Sav22999** [comment]
Fallo io la pr?

**Comment by Sav22999** [comment]
Vado di pr quindi?

**Comment by Mte90** [comment]
direi di si, fanne anche una che contiene tutto.
