### ISSUE TITLE
Testo rust da aggiornare

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/firefox-vademecum#56]
Nuovo testo per essere più semplice e accattivante:

`
Rust è un linguaggio di programmazione compilato multi-paradigma ideato da Mozilla in collaborazione con la comunità open source autonoma. L'obiettivo di Rust è di mettere a disposizione un linguaggio per creare sistemi complessi e sicuri, anche per il multithread. Ciò comporta un insieme di caratteristiche che enfatizzano le prestazioni, il controllo sull'allocazione di memoria e la sicurezza. Il progetto più famoso che lo utilizza è Firefox grazie ai componenti del motore di rendering Servo ma è utilizzato da molte aziende e progetti interessanti.
`

**Comment by mone27** [comment]
Forse riferendosi alla #38 ho pensato che si potrebbe parlare rapidamente di rust nel presentare le novità di Firefox 57, dicendo che permette di migliorare le prestazioni.
Poi nella sezione altri progetti (insieme a webVR...) si può mettere un link a una pagina con ulteriori informazioni.
 Così si può ridurre la parte tecnica del volantino.

**Comment by Mte90** [comment]
La sezione velocità nel volantino già c'è quindi potremo migliorare quella sezione sul tema.
Come proporresti di modificare questa sezione nello specifico?

**Comment by Mte90** [comment]
Altrimenti un alternativa è di togliere proprio rust che al pubblico a cui portiamo questo volantino essendo generico può non interessare e parlare delle versioni mobile di Firefox insieme a Firefox Focus.
