### ISSUE TITLE
Aggiornare sezione Test Pilot

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/firefox-vademecum#57]
Nuovo testo

`
Test Pilot è un progetto sviluppato da Mozilla che permette agli utenti di essere, in tutte le fasi di sviluppo, al centro del progetto Firefox provando delle estensioni sperimentali periodicamente. Si possono provare in anteprima delle possibili future funzionalità, prima che siano integrate nel browser stesso. Dopo averlo installato è possibile selezionare ciò che si desidera provare in anteprima e rilasciare un feedback sulla propria esperienza d’uso. Scopri le nuove funzionalità sperimentali su: https://testpilot.firefox.com/`

**Comment by Fastbyte01** [comment]
Forse suona meglio:
Test Pilot è un progetto sviluppato da Mozilla che permette agli utenti di essere, in tutte le fasi di sviluppo, al centro del progetto Firefox, testando periodicamente delle estensioni sperimentali. Si possono provare in anteprima delle possibili future funzionalità, prima che queste siano integrate nel browser stesso e rilasciate al grande pubblico. ....... 
Vieni a scoprire le nuove funzionalità sperimentali su:https://testpilot.firefox.com/```

**Comment by Mte90** [comment]
@edovio che ne pensi?
Secondo me manca la parte feedback che invece fa la differenza nel testo proposto da @Fastbyte01

**Comment by Fastbyte01** [comment]
@Mte90 Perdonami la parte feedback dovrebbe rimanere.

**Comment by Mte90** [comment]
`Test Pilot è un progetto sviluppato da Mozilla che permette agli utenti di essere, in tutte le fasi di sviluppo, al centro del progetto Firefox, testando periodicamente delle estensioni sperimentali. Si possono provare in anteprima delle possibili future funzionalità, prima che queste siano integrate nel browser stesso e rilasciate al grande pubblico. Dopo averlo installato è possibile selezionare ciò che si desidera provare in anteprima e rilasciare un feedback sulla propria esperienza d’uso. Vieni a scoprire le nuove funzionalità sperimentali su:https://testpilot.firefox.com/`
Quindi così va bene?

**Comment by Fastbyte01** [comment]
Yes, così secondo me va meglio. Vediamo che pensano anche gli altri.

Il giorno 22 novembre 2017 16:01, Daniele Scasciafratte <
notifications@github.com> ha scritto:

**Comment by Sav22999** [comment]
`Test Pilot è un progetto sviluppato da Mozilla e permette agli utenti di essere, in tutte le fasi di sviluppo, al centro del progetto Firefox, testando periodicamente delle estensioni sperimentali: si possono provare in anteprima delle possibili future funzionalità, prima che queste vengano integrate nel browser stesso e, quindi, disponibili per tutti. Dopo averlo installato è possibile scegliere ciò che si desidera provare, quindi collaborare rilasciando un feedback sulla propria esperienza d’uso. Vieni a scoprire le nuove funzionalità sperimentali su:https://testpilot.firefox.com/`

che ne dite di queste piccole modifiche?

**Comment by Mte90** [comment]
forse trovare un sostituto al termine `feedback` con `parere`? Per il resto mi sembra che vada bene.

**Comment by Sav22999** [comment]
Segnalazione?

**Comment by Mte90** [comment]
Forse in questo caso segnalazione può essere visto come c'è un problema e lo segnalo invece un parere è più del tipo mi piace ed ecco quello che ne penso.

**Comment by Sav22999** [comment]
Mh, si ci sta. Potrebbe andare anche bene "riscontro" 🤔

**Comment by Mte90** [comment]
Opinione mi suona ancora meglio.

**Comment by Sav22999** [comment]
Perfetto. E che "opinione" sia!

**Comment by Sav22999** [comment]
Vado di pr?

**Comment by Mte90** [comment]
Vai vai :-D

**Comment by Sav22999** [comment]
Io credo che qui suoni bene "lasciando la **tua** opinione", cosa ne pensi? Per rafforzare che ogni utente è importante, così come la loro opinione

**Comment by Mte90** [comment]
direi di si

**Comment by Sav22999** [comment]
Meglio ancora, credo, così:

> rilasciando una **propria** opinione sull’esperienza d’uso personale

**Comment by Mte90** [comment]
ho capito, hai vinto fai questa pr così vediamo tutto insieme 😂

**Comment by Sav22999** [comment]
Chiedo sempre prima di prendere decisione ahaha, rileggendo trovo miglioramenti (a mio avviso) e li segnalo ahaha

**Comment by Mte90** [comment]
tanto mica mordo, la pr ha la modalità revisione riga per riga su ogni modifica quindi poi è più facile discutere di questi dettagli lì.

**Comment by Sav22999** [comment]
Ah, giusto ahaha, mi dimentico delle tante funzionalità di gh
