### ISSUE TITLE
Aggiornare sezioni Perché scegliere Firefox?

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/firefox-vademecum#58]
Si potrebbero rendere queste sezioni più interessanti fornendo esempio reali come per il punto personalizzazione dei temi e container e di estensioni dicendo che alcuni esempi sono nella pagina successiva.

Per sicurezza parlare di Do Not Tracking e della modalità anonima.

Per velocità parlare del nuovo sistema multiprocesso.

**Comment by Sav22999** [comment]
Io proporrei di aggiornare la descrizione di Firefox, magari semplicemente mettendo in neretto alcune parole e modificando alcune parole. Io avrei pensato a qualcosa di simile:

> Firefox è creato **dagli** utenti **per** gli utenti. Non è creato per guadagnare, essendo indipendente da qualunque azienda, ma per **offrire** un'esperienza di navigazione unica.
Scegli il browser **libero**, **sicuro**, **affidabile** ed **indipendente**. Scegli Firefox!

**Comment by Mte90** [comment]
la pensata del grassetto non è male! vai e colpisci!

**Comment by Sav22999** [comment]
Ho cambiato anche il contenuto, cosa ne pensi?

**Comment by Mte90** [comment]
La parte ` creato per guadagnare essendo indipendente da qualunque azienda` la sostituirei con `nato per guadagnare, Mozilla è una fondazione no profit,`
Così rafforziamo il concetto, che ne dici?

**Comment by Sav22999** [comment]
Si, ci può stare. Alla fine non è una ripetizione, "Mozilla" non viene citata.

**Comment by Sav22999** [comment]
Vado di pr?

**Comment by Mte90** [comment]
Vai!

**Comment by Sav22999** [comment]
Sai cosa, invece di "nato" credo vada meglio "realizzato"... nato mi sembra come se nacque per non essere un guadagno ma ora lo è... cosa ne pensi?

**Comment by Mte90** [comment]
effettivamente hai ragione, abbiamo il termine adatto usiamolo
