### ISSUE TITLE
Riguardo i tre sistemi operativi

### ISSUE THREAD

**Issue by Fastbyte01** [MozillaItalia/firefox-vademecum#59]
Nel vademecum c'è questa frase: "il programma funzionerà allo stesso modo sui tre sistemi operativi principali".
Penso che andrebbe tolto il riferimento ai 3 sistemi operativi principali, in quanto le funzionalità principali e il livello di interazione con il browser ormai sono identici su tutte le piattaforme disponibili.

**Comment by Mte90** [comment]
Il contesto:
`Firefox è un software multipiattaforma in grado di funzionare sui sistemi operativi più diffusi (Windows, Linux, Mac OS X, Android e iOS): se per lavoro, per studio o per svago hai la necessità di dover utilizzare diverse piattaforme, il programma funzionerà allo stesso modo sui tre sistemi operativi principali, eliminando la necessità di imparare a utilizzare ogni volta un software diverso.`

Direi di fare:
`Firefox è un software multipiattaforma in grado di funzionare sui sistemi operativi più diffusi (Windows, Linux, Mac OS X, Android e iOS): se per lavoro, per studio o per svago hai la necessità di dover utilizzare diverse piattaforme, il programma avrà la stessa interfaccia da computer mentre da mobile l'esperienza sarà uniforme al sistema in uso.`

**Comment by Fastbyte01** [comment]
La tua versione va anche bene, l'unica cosa che mi sembra un pò "complessa"
è la frase "l'esperienza sarà uniforme al sistema in uso".

Il giorno 22 novembre 2017 15:55, Daniele Scasciafratte <
notifications@github.com> ha scritto:

**Comment by Mte90** [comment]
Direi che possiamo trovare un modo per cambiare quella parte con qualcosa di più semplice

**Comment by Fastbyte01** [comment]
@Mte90 ma fondalmentalmente l'uso rimane lo stesso, penso che alla fine cambia solo la grandezza dello schermo.

**Comment by Sav22999** [comment]
Io, "Mr Impersonalità" (autoproclamatomi oggi :P), consiglierei di rendere la frase più impersonale rimuovendo i vari riferimenti a "te/tu/ti..."

> Firefox è un software multipiattaforma in grado di funzionare sui sistemi operativi più diffusi (Windows, Linux, Mac OS X, Android e iOS): se per lavoro, per studio o per svago si ha la necessità di dover utilizzare diverse piattaforme, si avrà la stessa interfaccia da computer mentre da mobile l'esperienza sarà uniforme al sistema in uso. In entrambi i casi le funzionalità sono le medesime.

**Comment by Mte90** [comment]
Sul fattore impersonale c'era l'idea di fare una guida di regole di stile e questa cosa potrebbe essere ideale.
Per l'impersonale noi volevamo avere un tono più amichevole nel volantino, però provare uno stile impersonale non vuol dire "non amichevole".

**Comment by Sav22999** [comment]
Esatto. Io credo che l'impersonalità dia un certo rispetto... però è una mia cosa oggettiva... (e nella localizzazione, si cerca di evitare i possessivi generalmente)

**Comment by Mte90** [comment]
Allora direi di aggiungere la questione sul ticket delle regole di stile e intanto fai anche questa modifica.

**Comment by Sav22999** [comment]
Perfetto!

**Comment by Sav22999** [comment]
La frase finale che ho aggiunto va bene?

**Comment by Mte90** [comment]
si
