### ISSUE TITLE
Persone da aggiungere nei crediti

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/firefox-vademecum#61]
Serve una pr per aggiungere il nome di:

* Giuseppe Pignataro
* Saverio Morelli
* ...

Aspettiamo che altri facciano modifiche così aggiungiamo i nomi con un colpo solo.

**Comment by Sav22999** [comment]
Che onore

**Comment by Mte90** [comment]
Direi poi anche di fare il bump della versione del vademecum una volta che tutti i ticket sono fatti.

**Comment by Sav22999** [comment]
Questo credo sia molto veloce da risolvere. Si potrebbe procedere già con la pr

**Comment by Sav22999** [comment]
Integrato in README.md, non so cosa sia un bump però

**Comment by Mte90** [comment]
Il bump è quanto si passa al numero successivo di versione.
Cosa che abbiamo fatto
