### ISSUE TITLE
Spostare Readme.md in vademecum.md

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/firefox-vademecum#67]
In questo modo possiamo usare il readme per presentare il progetto

**Comment by Sav22999** [comment]
Questo issue lo devi chiudere per forza tu, io non credo possa creare file ".md"

**Comment by Sav22999** [comment]
Bugia, ho scoperto che posso farlo ahahah. Creiamo questo file così da chiudere (e "risolvere") anche questo ticket/issue?

**Comment by Mte90** [comment]
Ci serve del testo poi per il readme quindi fai una pr così poi lo revisioniamo di là che è più facile

**Comment by Sav22999** [comment]
Certo
