### ISSUE TITLE
Modificare/Aggiornare la "Modalità lettura"

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/firefox-vademecum#68]
Io consiglierei di modificare la descrizione. Proporrei qualcosa di simile a quanto segue:
> La modalità lettura è una funzionalità di Firefox e permette di visualizzare, di una specifica pagina, **solo il testo ed le immagini**, rimuovendo tutto il resto. E' altamente **personalizzabile**: si può modificare l'interlinea, i margini, la grandezza del testo e molto altro. Inoltre è possibile mettersi comodi ed **ascoltare** quella stessa pagina, senza doverla leggere, grazie al pulsante "**Leggi ad alta voce**"!

**Comment by Mte90** [comment]
per me va bene, non so se `di una specifica pagina` è di troppo.

**Comment by Sav22999** [comment]
🤔 magari 

> qualunque pagina che la supporti

**Comment by Mte90** [comment]
io punto al conciso, dopo bisogna convertire il volantino in un a4 e spesso qualcosa va tagliato. se riusciamo ad essere brevi ne guadagniamo.

**Comment by Sav22999** [comment]
Non so come abbreviarla ulteriormente...

**Comment by Mte90** [comment]
e allora lascia così poi quando prove®ò a fare il nuovo volantino vedrò se tagliare da altre parti :-D

**Comment by Sav22999** [comment]
Non ho capito, nella pr modifico anche la modalità lettura secondo ciò che ho detto io?

**Comment by Sav22999** [comment]
Comunque, per abbreviare, potremmo evitare di dire "La modalità lettura è ..." e scrivere direttamente "E' ..."

**Comment by Mte90** [comment]
si vai con la tua modifica poi sul conciso me la vedo quando faccio la versione da stampa

**Comment by Mte90** [comment]
dovremmo farlo in tutte le sezioni perché mi pare che ci ripetiamo su quella falsa riga

**Comment by Sav22999** [comment]
Si, infatti, per risparmiare spazio si potrebbero omettere
