### ISSUE TITLE
Valorizzare le estensioni di Firefox, anche sul mobile

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/firefox-vademecum#69]
Io consiglierei di valorizzare maggiormente le estensioni, facendo riferimento alla compatibilità sulle app mobile, a differenza degli altri maggiori web browser. che ne pensate? Alla fine chrome, opera, edge, eccetera non hanno (ancora, per lo meno) le estensioni per mobile, quindi potrebbe essere un grande punto di forza, a mio avviso.

**Comment by Mte90** [comment]
Abbiamo una sezione sul mobile? non mi ricordo se no direi di citare qualcosa nella sezione estensioni come dici tu.
Dopotutto ff for android è l'unico browser mobile che le supporta.

**Comment by Sav22999** [comment]
Esattamente! Nel volantino non mi pare di aver letto qualcosa inerente al mobile, strettamente. Solo quella citazione dei sistemi operativi e credo basta

**Comment by Mte90** [comment]
Allora direi di menzionare nell'incipit delle estensioni

**Comment by Sav22999** [comment]
Sinceramente penso di star diventando meglio di un computer, multitasking, vado da un issue ad un altro hahahahah

**Comment by Mte90** [comment]
Io tra email e notifiche sul browser ti seguo a ruota :-P

**Comment by Sav22999** [comment]
Cosa ne pensi di:

> Il punto di forza di Firefox sono le estensioni. La libertà e la personalizzazione del browser sono le caratteristiche di Firefox, a dimostrazione del fatto che gli utenti sono di massima importanza per Mozilla. Firefox, inoltre, è il solo web browser che dispone delle stesse estensioni anche nelle versioni mobile. Qui di seguito alcune delle migliori estensioni disponibili:

Io rimuoverei Fondazione Mozilla lasciando solo Mozilla, o per lo meno lasciandola in inglese visto che sopra è stata riportata come Mozilla Foundation: sembrano 2 cose distinte.

**Comment by Mte90** [comment]
Il testo mi va bene toglierei la parte di riferimento riguardo che le
stesse si trovano su mobile perché non tutte sono disponibili

**Comment by Sav22999** [comment]
> Il punto di forza di Firefox sono le estensioni. La libertà e la personalizzazione del browser sono le caratteristiche di Firefox, a dimostrazione del fatto che gli utenti sono di massima importanza per Mozilla. Firefox, inoltre, è il solo web browser che dispone di estensioni anche nella versione mobile. Qui di seguito alcune delle migliori estensioni disponibili:

così?

**Comment by Mte90** [comment]
👍

**Comment by Sav22999** [comment]
Procedo col pr

**Comment by Sav22999** [comment]
Procedo con la pr?
