### ISSUE TITLE
Sezioni da abbreviare

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/firefox-vademecum#83]
Salve a tutti, nella creazione dell'HTML mi sono accorto che la sezione libertà e personalizzazione è davvero troppo lunga e non entra negli spazi previsti...
io la sostituirei con questa (c'è una riduzione di 200+ caratteri, rispetto a quella passata)

> Firefox è il browser davvero “personale”. È possibile aggiungere nuove funzionalità, grazie alle migliaia di estensioni disponibili e, in caso non dovessi trovarla, puoi svilupparla tu stesso. Si può personalizzare anche l'interfaccia grafica, grazie alla moltitudine di temi e, anche in questo caso, se non dovessi trovare qualcosa che ti piace, puoi crearne uno tutto tuo!

**Comment by Sav22999** [comment]
Modalità lettura

> La modalità lettura è una funzionalità di Firefox che permette di visualizzare, di una qualunque pagina che la supporti, solo il testo e le immagini, rimuovendo tutto il resto. E' altamente personalizzabile e ricca di funzionalità come il "Leggi ad alta voce"!

**Comment by Sav22999** [comment]
Firefox For Developers e Firefox Nightly

> Firefox Dev Edition è una versione basata sulla Beta, attiva in modo predefinito delle opzioni dedicate agli sviluppatori.
Firefox Nightly è una versione di sviluppo aggiornata giornalmente che permette di provare le ultime funzionalità. Utilizzata per segnalare problemi sia di traduzione sia di funzionalità.

**Comment by Sav22999** [comment]
I Don't Care About Cookies

>È possibile disattivare gli avvisi, obbligatori, sull'uso di cookie di terze parti imposto da una direttiva dell'UE.

**Comment by Sav22999** [comment]
HTTPS Everywhere

> Alcuni siti non hanno il protocollo HTTPS attivato e la navigazione, pertanto, non è protetta. Questa estensione forzerà l'attivazione, rendendo la navigazione sicure e protetta.

**Comment by Sav22999** [comment]
Firefox Focus

> Firefox Focus è un nuovo progetto della Mozilla Foundation che porta la navigazione privata a un livello più alto, fornendo un browser dedicato alla privacy, attraverso un evoluto sistema di protezione antitracciamento e di blocco dei contenuti. Le avanzate funzionalità per la protezione della privacy sono sempre attive e la cronologia di navigazione, come anche i dati raccolti, vengono eliminati automaticamente al termine di ogni sessione di navigazione. Tutte queste caratteristiche avanzate sono disponibili in solo 5 MB, sia per Android sia per iOS.

**Comment by Mte90** [comment]
Mi vanno tutti bene
