### ISSUE TITLE
Rimozione di alcune "Novità" non nuove

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/firefox-vademecum#85]
Io proporrei di rimuovere dalla sezione "Novità":
- Modalità lettura
- Pulsante dimentica
- Firefox for Developers e Firefox Nightly

per due ragioni:
1. Non sono novità, infatti nell'edizione passata del vademecum erano già presenti
2. Spazio insufficiente per inserire altro... praticamento NON entra "Altri progetti Mozilla" (e ciò che segue)

**Comment by Mte90** [comment]
Io sono per togliere i primi due mentre noi promuoviamo la nightly in continuazione e dobbiamo lasciarla.

**Comment by Sav22999** [comment]
Non ha gran senso rimuovere solo i primi 2 allora, sempre quello è lo spazio e si risparmi poco, quindi li lasciamo tutti (vedi le pagine che ho messo in /html/ nel mio repository, "retro_volantino.html"... questi sono sottoforma di commento, ma comunque li ho inseriti. Non entra più niente....)

**Comment by Mte90** [comment]
Qual'é il ramo?

**Comment by Sav22999** [comment]
17

**Comment by Sav22999** [comment]
Cosa facciamo con questo issue... io credo che sia possibile chiuderlo o no?
