### ISSUE TITLE
Rimozione "Test Pilot" come altro progetto Mozilla "dettagliato"

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/firefox-vademecum#86]
Io proporrei di rimuovere "Test Pilot" da "Altri progetti Mozilla" principalemente per problemi di spazio, ed anche perchè già nel precedente volantino era presente... quindi è meglio "cambiare".
Ovviamente verrebbe incluso nei progetti citati, ma non dettagliati.
Datemi le vostre opinioni

**Comment by Mte90** [comment]
Io lo lascerei perché è un progetto che si rinnova in continuazione e non muore.

**Comment by Sav22999** [comment]
Capisco... però io non so come farlo entrare nella pagina... sono veramente troppi contenuti... non entra neppure il "Vuoi contribuire?" ed i "Crediti"

**Comment by Mte90** [comment]
se vedi la versione pdf c'eravamo riusciti ma la parte vuoi contribuire l'avevamo tolta.

**Comment by Sav22999** [comment]
Si, ho visto... dovremmo ridurre la dimensione del testo, da 12 a 10

**Comment by Sav22999** [comment]
Io direi che questo issue è possibile chiuderlo, o no?
è stato deciso che "Test Pilot" è in continuo rinnovamento, quindi è un progetto di notevole importanza.
