### ISSUE TITLE
Integrare Stylo

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/firefox-vademecum#90]
Nella sezione "Velocità" di "Perché scegliere Firefox?" si potrebbe citare Stylo, o no? 
O magari come Novità

**Comment by Mte90** [comment]
Sembra un dettaglio troppo tecnico specificare i nomi dei componenti interni come gecko.
Poi la domanda principale è: abbiamo spazio per mettere altre informazioni? Perchè in caso abbiamo altro materiale a cui dare priorità :-D

**Comment by Sav22999** [comment]
Purtroppo non c'è spazio per niente... però credo che citarlo almeno, mettendo la pulce nell'orecchio e rimandando a pagine esterne per approfondire sia interessante... Non so. Queste è il mio parere modestissimo

**Comment by Mte90** [comment]
Io credo che non sia utile menzionarlo, avrebbe più senso menzionare altro anche perchè Stylo è solo una parte della tecnologia. Avrebbe più senso parlare di Webrender ma ad un pubblico generico a cui puntiamo con questo volantino sarebbe solo qualche termine in più da studiare.
Se menzioniamo Stylo dovremmo menzionare molte altre cose per dare il contesto delle novità.

**Comment by Sav22999** [comment]
Perfetto. Quindi chiudiamo questo issue in quanto la soluzione è presa.
:)
