### ISSUE TITLE
Aggiornare estensioni

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/firefox-vademecum#91]
Io credo che dovremmo aggironare le estensioni. Va bene che quelle citate sono molto usate, aggiornate e tutto quel che si vuole. Ma credo che mettere le stesse dello scorso volantino sia una ripetizione.
Io lascerei uBlock Origin, HTTPS Everywhere, History AutoDelete, rimuovendo gli altri.
Potremmo aggiungere Video DownloadHelper (o alternative), Facebook Container, Hoxx VPN Proxy (o alternative), ...

**Comment by Mte90** [comment]
Video DownloadHelper c'era nelle prime versioni e sono d'accordo per facebook container.
Per me possiamo togliere Lightbeam e sostituirlo con quello.
Le estensioni di esempio sono delle cose che possono essere utili a tutti e che possono invogliare a dire proviamolo, spesso non sanno la questione adblock o dei cookie quindi io quelli li terrei.

**Comment by Sav22999** [comment]
Sisi uBlock anche io lo terrei. Era anche per ottimizzare lo spazio... qui si aggiunge solo e non si rimuove niente (giustamente, perché sono cose importanti)

**Comment by Mte90** [comment]
Allora direi che puoi andare con facebook container e rimuovere lightbeam :-)

**Comment by Sav22999** [comment]
E che ne pensi di un client VPN?

**Comment by Sav22999** [comment]
@Mte90 un'osservazione. Non si potrebbe realizzare un volantino "generico" ed uno più "tecnico"? Nel senso, uno indirizzato a tutti, comunque, mentre un altro indirizzato piuttosto ai tecnici?

**Comment by Mte90** [comment]
Si potrebbe anche fare ma direi prima finiamo quello generico così abbiamo anche la versione html e poi con il tecnico andiamo più spediti senza confonderci le cose.

**Comment by Sav22999** [comment]
Essi, magari in quello generico si potrebbe togliere anche quelle novità. Perchè mia mamma non credo sappia cos'è Pocket, o cos'è uno screenshot, e non penso proprio le interessi una "barra degli indirizzi intelligente"... correggetemi se sbaglio, ma credo siano "chicche" più tecniche che altro

**Comment by Mte90** [comment]
Eh si sono cose che ti devono invogliare a provarle e quindi meno sono tecniche ma interessanti e più probabilità ci sono che la persona si tiene il volantino e poi le provi.

**Comment by Sav22999** [comment]
quindi?

**Comment by Mte90** [comment]
Io vorrei provare a lasciarle al limite non le mettiamo tutte.

**Comment by Sav22999** [comment]
Stiamo uscendo fuori tema, apro un altro issue

**Comment by Sav22999** [comment]
Quindi, in conclusione, come ci comportiamo con le estensioni?

**Comment by Sav22999** [comment]
Quali lasciamo? Quali aggiungiamo? e quali rimuoviamo?

**Comment by Sav22999** [comment]
Io sono rimasto col rimanere tutto tranne Lightbeam che verrebbe sostituito da Facebook Container

**Comment by Sav22999** [comment]
Io credo che venga una cosa più carica se sono sei, quindi basta levare lightbeam sostituendolo con facebook container, oppure se vuoi togliere anche history autodelete dobbiamo trovare un sostituto, oppure ditemi come procedere :)

(Facebook Container, uBlock Origin, Privacy Badger, IDCAC, HTTPS Everywhere e History AutoDelete)

**Comment by Mte90** [comment]
Decidiamo o tagliare o sostituire sennò non ce la faremo mai XD

**Comment by Sav22999** [comment]
No, avendo spostato la sezione "Novità" nella pagina_fronte, entrano più cose, quindi ci stanno 6 estensioni xD

**Comment by Mte90** [comment]
Allora per il momento facciamo solo Lightbeam e vediamo che effetto che fanno.
