### ISSUE TITLE
Volantino "generico" e "tecnico"

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/firefox-vademecum#92]
generico: rivolto a chiunque, anche senza conoscenze tecniche
tecnico: con termini più "spinti" nella tecnologia, termini più proprio e precisi

**Comment by Sav22999** [comment]
Se quello generico è (diciamo) concluso potremmo pensare di realizzare anche quello tecnico (?)

**Comment by Mte90** [comment]
io direi di farlo revisionare alla comunità, mi segno di fare un post sul forum così vediamo cosa ne pensa tutta la comunità :-)

**Comment by Sav22999** [comment]
Certo! Non sapevo come si dovesse procedere :)
________________________________

**Comment by Sav22999** [comment]
La versione tecnica è stata avviata, pertanto questo issue è da considerarsi concluso (è stata presa la decisione di realizzare anche la VT)
