### ISSUE TITLE
Ridurre il volantino....

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/firefox-vademecum#93]
Nella versione HTML è possibile vedere che non entrano tutte le sezioni, quindi dobbiamo cercare in qualche modo di ridurre...

**Comment by Mte90** [comment]
fai delle proposte di testo che possiamo togliere

**Comment by Sav22999** [comment]
se vengono approvate delle "rimodulazioni" apriamo degli issue a parte, così da lasciare questo solo per le idee, da approvare o meno

**Comment by Sav22999** [comment]
Dunque ora la sezioni "Novità" è possibile spostarla nel fronte del volantino.
Ci entrano solo 3 novità. Quali dovremmo tenere in dettaglio? Le altre io le citerei solo... altrimenti lo spazio non basta nuovamente...
Io terrei solamente "Barra degli indirizzi intelligente", "Firefox screenshot" e "Pocket". Il resto nella descrizione solamente.

Dite la vostra

**Comment by Mte90** [comment]
dire che può andare :-)

**Comment by Sav22999** [comment]
Per le estensioni, invece? Le modifichiamo?

**Comment by Sav22999** [comment]
penso che anche questo issue può essere chiuso
