### ISSUE TITLE
Unire INTRODUZIONE e MOZILLA, FIREFOX E MOZILLA ITALIA

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/firefox-vademecum#94]

**Comment by Sav22999** [comment]
Io modificherei, prima di tutto il titolo in "Presentazione" (ingloba entrambe le sezioni)
Dopodiché questo sarebbe il testo che io propongo:

> Questa guida si prefigge l'obiettivo di illustrare **brevemente** il mondo di Firefox e tutto ciò che lo circonda.
Prima di tutto è doveroso spiegare cos'è _Firefox_. Ebbene, è un browser web **unico**: mette al primo posto gli utente, ha il codice sorgente libero (quindi tutti possono analizzarlo), è disponibile su tutti i principali sistemi operativi, è personalizzabile, versatile, veloce e, molto importante, **sicuro**.
**Mozilla Foundation** è l'organizzazione _senza scopi di lucro_ che supporta Firefox ed altri numerosi progetti. Questa organizzazione è formata da **volontari** provenienti da ogni parte del _globo_.
La comunità che opera in Italia prende il nome di _Mozilla Italia_; si occupa di tradurre progetti, siti web, ma anche di realizzare e partecipare ad eventi, e molto altro.
Per queste ragioni chiunque è il benvenuto: **collaborare** è il fulcro di ogni comunità.

**Comment by Mte90** [comment]
è una guida o un volantino direi che dobbiamo definire questa parte :-D

Mozilla foundation non è formata da volontari, ha molti volontari che ecc

**Comment by Sav22999** [comment]
Perfetto, modifico direttamente il messaggio

**Comment by Sav22999** [comment]
Io direi "presentazione", mi suona male "Questo volantino si ..."

**Comment by Sav22999** [comment]
(quando hai tempo che lo leggi fammi sapere un'opinione. Se è troppo breve, se manca qualcosa o se si può procedere alla pr)

**Comment by Mte90** [comment]
Se rimuovessimo la prima riga direttamente? salviamo spazio e possiamo parlare di altro così ed evitiamo il problema della introduzione.

**Comment by Sav22999** [comment]
Sì, certo. A me sta bene 👍

**Comment by Sav22999** [comment]
> ## Presentazione
Prima di tutto è doveroso spiegare cos'è Firefox. Ebbene, è un browser web unico: mette al primo posto gli utente, ha il codice sorgente libero (quindi tutti possono analizzarlo e modificarlo), è disponibile su tutti i principali sistemi operativi, è personalizzabile, è versatile, è veloce e, molto importante, è sicuro.
Mozilla Foundation è l'organizzazione senza scopi di lucro che, dal oltre 15 anni, supporta Firefox ed altri numerosi progetti. Questa organizzazione ha più di 10.000 volontari, provenienti da ogni parte del globo.
La comunità che opera in Italia prende il nome di Mozilla Italia; si occupa di tradurre progetti, siti web, ma anche di realizzare e partecipare ad eventi, e molto altro.
Per queste ragioni chiunque è il benvenuto: collaborare è il fulcro di ogni comunità.

**Comment by Mte90** [comment]
Mi sembra a posto così a parte la parte `al primo posto gli utente` dove l'ultima parola ha un errore di battitura immagino.

Vai di pr se non hai altre modifiche da proporre!

**Comment by Sav22999** [comment]
ahah, nono, volevo sbagliare volontariamente (certo che è un errore di battitura 😜 )

**Comment by Sav22999** [comment]
Mh, un'altra modifica potrebbe essere quella di aggiungere il canale telegram di mozilla italia

**Comment by Mte90** [comment]
Credo che a livello grafico potremmo farlo mettendo l'icona di telegram con il nome da cercare ma forse con la riga risparmiata ora ce la facciamo!

**Comment by Sav22999** [comment]
chiudo l'issue dal momento che la pr è stata accettata
