### ISSUE TITLE
Modificare sezione Novità

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/firefox-vademecum#96]
Rimuovere dalla sezione novità le subsezioni "Firefox dev edition", "pulsante dimentica" e "modalità lettura"

**Comment by Sav22999** [comment]
Inoltre aggiornare la descrizione.
Io avrei pensato a questa:

> Gli aggiornamenti di Firefox mirano a migliorare l'esperienza utente, quindi aggiungendo funzionalità utili e richieste.
Alcune funzionalità utili sono: **modalità lettura**, **pulsante dimentica**.
Firefox dispone di due varianti versioni, oltre alla stabile, la _Dev Edition_, rivolta agli sviluppatori, e la _Nightly_, rivolta a chi vuole collaborare segnalando eventuali problemi.

**Comment by Mte90** [comment]
Cambierei questa frase: `Alcune funzionalità utili sono: modalità lettura, pulsante dimentica.` con `Alcune di queste funzionalità: modalità lettura, pulsante dimentica {altre se ci servono}.`

Poi cambierei `Firefox dispone di due varianti versioni, oltre alla stabile, la Dev Edition, rivolta agli sviluppatori, e la Nightly, rivolta a chi vuole collaborare segnalando eventuali problemi.` con `Firefox offre diverse versioni, oltre alla stabile, la Dev Edition, rivolta agli sviluppatori, e la Nightly, rivolta a chi vuole collaborare segnalando eventuali problemi.`

**Comment by Sav22999** [comment]
Perfetto, aggiornato con

> Gli aggiornamenti di Firefox mirano a migliorare l'esperienza utente, quindi aggiungendo funzionalità utili e richieste.
Alcune di queste funzionalità sono: **modalità lettura**, **pulsante dimentica** [altre].
Firefox offre diverse versioni, oltre alla stabile, la _Dev Edition_, rivolta agli sviluppatori, e la _Nightly_, rivolta a chi vuole collaborare segnalando eventuali problemi.

**Comment by Mte90** [comment]
Direi che va bene e se non abbiamo altro da aggiungere togliere anche quel segnaposto.

**Comment by Sav22999** [comment]
Non so, magari ci vengono in mente più in la. Comunque nel volantino non comparirebbe xD
