### ISSUE TITLE
Facebook Container al posto di Lightbeam in Estensioni

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/firefox-vademecum#97]
Sostituire, nella sezione Estensioni, Lightbeam con Facebook Container.
Avrei pensato a questa descrizione:

> Questo componente aggiuntivo **isola** automaticamente Facebook impedendogli di raccogliere dati e attività registrate su altri siti. Avviene mediante un contenitore, che si attiva in automatico e identificabile da una linea blu inferiore.

Suggerimenti graditi ed accetti

**Comment by Sav22999** [comment]
Certo, quali sono? xD

**Comment by Mte90** [comment]
Facebook, instagram Whatsapp e Messenger :-)

**Comment by Sav22999** [comment]
Perfetto, io modificherei così:

> Questo componente aggiuntivo **isola** automaticamente i servizi di Facebook impedendogli di raccogliere dati e attività registrate su altri siti. Avviene mediante un contenitore, che si attiva in automatico e identificabile da una linea blu inferiore.

**Comment by Mte90** [comment]
quali servizi di Facebook ti direi :-) non tutti sanno che instagram è di Facebook e menzionare certi servizi come Whatsapp attira l'attenzione.

**Comment by Sav22999** [comment]
Perfetto, avevo stimato 255 caratteri massimo, quindi vediamo un po' di ristrutturarlo magari. Comunque, eventuali modifiche le apportiamo dopo. Ora vediamo dove elencarli xD

**Comment by Mte90** [comment]
`Questo componente aggiuntivo isola Facebook, WhatsApp, Messenger e Instagram impedendogli di raccogliere dati e attività registrate su altri siti. Avviene mediante un contenitore in automatico e identificabile da una linea blu inferiore sulla scheda.`

Così salviamo lo spazio perso :-D

**Comment by Sav22999** [comment]
... secondo me è meglio con "che si attiva", non si capisce 🙄

**Comment by Mte90** [comment]
Con `Questo componente aggiuntivo isola Facebook, WhatsApp, Messenger e Instagram impedendogli di raccogliere dati e attività registrate su altri siti. Avviene attivando un contenitore in automatico e identificabile da una linea blu inferiore sulla scheda.` ?

**Comment by Sav22999** [comment]
Così mi sembra come se bisogna attivare un contenitore che si attiva in automatico, 🙄  xD xD SORRY

**Comment by Mte90** [comment]
Urgh hai ragione, hai vinto tu.

**Comment by Sav22999** [comment]
Nono, non voglio che mi dai ragione. Cerchiamo un'alternativa che accontenti entrambi ...

**Comment by Sav22999** [comment]
Così, ancora meglio xD

> Questo componente aggiuntivo **isola** Facebook, WhatsApp, Messenger e Instagram impedendogli di raccogliere dati e attività registrate su altri siti. Avviene mediante un contenitore, che si attiva in automatico e identificabile da una linea blu presente sulla scheda.

**Comment by Mte90** [comment]
Ok
