### ISSUE TITLE
Dimezzare la sezione "WebVR"

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/firefox-vademecum#98]
E' troppo lunga

>  La realtà virtuale oggi permette di sperimentare nuove possibilità, anche unita alla realtà aumentata. Queste tecnologie oggi richiedono costosi headset, dispositivi potenti e specifici. Tutto ciò si può risolvere grazie al web, grazie a Firefox, sia da mobile sia da desktop. In Mozilla è stata creata una comunità che si occupa di promuovere e sperimentare ciò, con la libreria JavaScript A-Frame, specifica per la VR: http://mozvr.com 

(447)

Portarla a circa 210 caratteri (massimo)

**Comment by Sav22999** [comment]
Vediamo se così va bene... non viene citata la comunità dedicata in Mozilla ma io non ho alcun idea:

> La realtà virtuale oggi permette di sperimentare nuove possibilità, anche unita alla realtà aumentata.
Queste tecnologie richiedono costosi headset ma, **grazie a Firefox**, è possibile farlo direttamente sul web, sia da mobile sia da desktop, utilizzando la libreria JavaScript A-Frame.

**Comment by Sav22999** [comment]
Altrimenti si potrebbe rimuovere l'introduzione:

> La realtà virtuale e quella aumentata richiedono costosi e specifici dispositivi, gli headset, ma, grazie a Firefox, è possibile farlo direttamente dal web con la libreria JavaScript A-Frame.

**Comment by Mte90** [comment]
Si via l'introduzione però il secondo commento mi va bene

**Comment by Sav22999** [comment]
Questo?

> La realtà virtuale e quella aumentata richiedono costosi e specifici dispositivi, gli headset, ma, grazie a Firefox, è possibile farlo direttamente dal web con la libreria JavaScript A-Frame.

**Comment by Mte90** [comment]
questo mi sembra perfetto https://github.com/MozillaItalia/firefox-vademecum/issues/98#issuecomment-384073627

**Comment by Sav22999** [comment]
Il fatto è che sono 249 caratteri, non entra nel foglio xD (questo cavolo di foglio!!!)

**Comment by Sav22999** [comment]
Altrimenti metto 11px come grandezza invece di 12px

**Comment by Mte90** [comment]
Direi che 11 siano leggibili su cartaceo, facciamo una prova!

**Comment by Sav22999** [comment]
Si, non so come viene infatti. Casomai riduciamo in seguito! Perfetto
